# Generated by Django 3.0.14 on 2021-05-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='summary',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='visits',
            field=models.SmallIntegerField(default=0),
        ),
    ]
